# -*- mode: toml-ts; -*- vim:ft=toml

[general]
import = [ "themes/alice.toml" ]

[window]
padding = { x = 8, y = 8 }
decorations = "None"
opacity = 0.95

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Medium" }
italic = { family = "JetBrains Mono", style = "Italic" }
bold_italic = { family = "JetBrains Mono", style = "Medium Italic" }
size = 14.00

[cursor]
style = { shape = "Beam", blinking = "On" }

