#!/bin/sh

case $1 in

    count)
        printf '%s\n' "$(checkupdates | wc -l)";
        ;;

    names)
        printf '%s\n' "$(checkupdates | perl -F'\x20' -lane 'print @F[0]')";
        ;;
    refresh)
        eww update pacman-count="$(checkupdates | wc -l)";
        ;;
    popup)
        eww open pacman-popup
        ;;
    *)
        exit 1;
        ;;

esac
