#!/bin/sh

key_file="${HOME}/.ssh/id_ed25519"

mkdir -p "${XDG_RUNTIME_DIR}/sockets"
chmod 0700 "${XDG_RUNTIME_DIR}/sockets"
SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/sockets/ssh-agent"
export SSH_AUTH_SOCK
ssh-agent -D -a "${SSH_AUTH_SOCK}" &
ssh-add "$key_file"
