# SPDX-FileCopyrightText: 2025 2025 Will Reed <wreed@disroot.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
- hosts: localhost
  connection: local
  become: false

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    gnupghome: "{{ lookup('env', 'GNUPGHOME') | default(home ~ '/.local/share/gnupg') }}"
    xdgconfig: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(home ~ '/.config') }}"
    xdgstate: "{{ lookup('env', 'XDG_STATE_HOME') | default(home ~ '/.local/state') }}"
    xdgdata: "{{ lookup('env', 'XDG_DATA_HOME') | default(home ~ '/.local/share') }}"
    xdgcache: "{{ lookup('env', 'XDG_CACHE_HOME') | default(home ~ '/.cache') }}"
    cargohome: "{{ lookup('env', 'CARGO_HOME') | default(home ~ '/.local/share/rust') }}"
    gopath: "{{ lookup('env', 'GOPATH') | default(home ~ '/.local/share/go') }}"

  tasks:
  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
    - "{{ xdgconfig }}"
    - "{{ xdgstate }}"
    - "{{ xdgdata }}"
    - "{{ xdgcache }}"
    - "{{ cargohome }}"
    - "{{ gopath }}"
    tags: dirs

  - name: wireplumber configuration (desktop)
    file:
      src: "{{ playbook_dir }}/files/.config/wireplumber/wireplumber.conf.d/51-local.conf.desktop"
      dest: "{{ xdgconfig }}/wireplumber/wireplumber.conf.d/51-local.conf"
      state: link
      force: yes
    when: ansible_facts['form_factor'] == "Desktop"
    tags: config

  - name: wireplumber configuration (laptop)
    file:
      src: "{{ playbook_dir }}/files/.config/wireplumber/wireplumber.conf.d/51-local.conf.laptop"
      dest: "{{ xdgconfig }}/wireplumber/wireplumber.conf.d/51-local.conf"
      state: link
      force: yes
    when: ansible_facts['form_factor'] == "Notebook"
    tags: config

  - name: create config directories
    file:
      path: "{{ xdgconfig }}/{{ item }}"
      state: directory
      mode: '0755'
    loop:
    - alacritty/themes
    - bash
    - bat
    - bottom
    - emacs
    - fastfetch
    - fish
    - fontconfig
    - foot
    - fuzzel
    - ghostty
    - git
    - glow
    - guile
    - hypr
    - kanshi
    - kitty
    - mpd
    - mpv
    - ncdu
    - nix
    - nvim
    - ov
    - pacman
    - rmpc
    - rust
    - starship
    - swhkd
    - tofi
    - tree-sitter
    - vesktop/themes
    - waybar
    - wezterm
    - wget
    - wireplumber/wireplumber.conf.d
    - zathura
    - zed
    - zsh
    tags: dirs

  - name: link home dotfiles
    file:
      src: "{{ playbook_dir }}/files/{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
      force: yes
    loop:
    - { src: "bashrc", dest: "~/.bashrc" }
    - { src: "bashrc", dest: "~/.bash_profile" }
    - { src: "profile", dest: "~/.profile" }
    - { src: "gnupg/gpg.conf", dest: "{{ gnupghome }}/gpg.conf" }
    - { src: "gnupg/dirmngr.conf", dest: "{{ gnupghome }}/dirmngr.conf" }
    tags: config

  - name: link config dirs and files
    file:
      src: "{{ playbook_dir }}/files/.config/{{ item }}"
      dest: "{{ xdgconfig }}/{{ item }}"
      state: link
      force: yes
    loop:
    - alacritty/alacritty.toml
    - alacritty/themes
    - bash/aliases.bash
    - bash/functions.bash
    - bat/config
    - bottom/bottom.toml
    - curlrc
    - fastfetch/config.jsonc
    - fish/config.fish
    - fish/functions
    - fish/conf.d
    - fontconfig/fonts.conf
    - foot/foot.ini
    - foot/themes
    - fuzzel/fuzzel.ini
    - fuzzel/themes
    - ghostty/config
    - ghostty/themes
    - git/config
    - glow/glow.yml
    - guile/init.scm
    - hypr/config.hl
    - hypr/env.hl
    - hypr/keys.hl
    - hypr/lock.hl
    - hypr/rules.hl
    - hypr/theme.hl
    - hypr/themes
    - kanshi/config
    - kitty/kitty.conf
    - kitty/symbols.conf
    - kitty/themes
    - mimeapps.list
    - mpd/mpd.conf
    - mpv/mpv.conf
    - ncdu/config
    - nix/nix.conf
    - nvim/init.lua
    - nvim/lua
    - ov/config.yaml
    - pacman/makepkg.conf
    - rmpc/config.ron
    - rust/config.toml
    - starship/config.toml
    - swhkd/swhkdrc
    - tofi/config
    - tofi/themes
    - tree-sitter/config.json
    - user-dirs.dirs
    - vesktop/themes/fonts.css
    - waybar/config.jsonc
    - waybar/main.sass
    - waybar/color-schemes
    - wezterm/alice.lua
    - wezterm/wezterm.lua
    - wget/wget2rc
    - zathura/zathurarc
    - zed/settings.json
    - zsh/.zshenv
    - zsh/.zshrc
    - zsh/hooks
    tags: config
