#!/bin/zsh -l

source "/etc/zsh/zprofile"
source "${HOME}/.zshenv"
source "${HOME}/.config/zsh/.zshrc"

riverctl map normal Super Return spawn "${TERMINAL}"
riverctl map normal Super P spawn "${LAUNCHER}"
riverctl map normal Super+Shift B "${BROWSER}"
riverctl map normal Super+Shift E "${VISUAL}"

riverctl map normal Super+Shift C close
riverctl map normal Super+Shift X exit

riverctl map normal Super       J focus-view next
riverctl map normal Super       K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super       H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super       L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Alt H move left  100
riverctl map normal Super+Alt J move down  100
riverctl map normal Super+Alt K move up    100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical    100
riverctl map normal Super+Alt+Shift K resize vertical   -100
riverctl map normal Super+Alt+Shift L resize horizontal  100

riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_RIGHT  resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super       $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags    $tags
done

riverctl map normal Super       F toggle-float
riverctl map normal Super+Shift F toggle-fullscreen

riverctl background-color       0x21222C
riverctl border-color-focused   0x6272A4
riverctl border-color-unfocused 0x282A36

riverctl set-repeat 50 300
riverctl focus-follows-cursor normal
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl xcursor-theme "Phinger-Light" 36

riverctl rule-add float -app-id '*xfce*'
riverctl rule-add float -app-id '*avucontro*'
riverctl rule-add ssd   -app-id "*irefox"
riverctl rule-add ssd   -app-id "*xfce*"
riverctl rule-add ssd   -app-id "*avucontro*"
riverctl rule-add csd   -app-id "*wezterm*"

gsettings set org.gnome.desktop.interface gtk-theme "Kripton"
gsettings set org.gnome.desktop.interface icon-theme "Tela-dark"
gsettings set org.gnome.desktop.interface cursor-theme "Phinger-Light"
gsettings set org.gnome.desktop.interface cursor-size 36
gsettings set org.gnome.desktop.wm.preferences theme "Kripton"
gsettings set org.gtk.Settings.FileChooser show-hidden true
gsettings set org.gtk.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true
gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true

pgrep -x xfsettingsd >/dev/null || env -u WAYLAND_DISPLAY xfsettingsd -D --replace --daemon &
pgrep -x swaybg      >/dev/null || swaybg --mode fit --image ~/pictures/wallpapers/default.png &
pgrep -x wlsunset    >/dev/null || wlsunset &

pgrep -x rivertile >/dev/null || riverctl default-layout rivertile
pgrep -x rivertile >/dev/null || rivertile \
    -main-count    1 \
    -view-padding  5 \
    -outer-padding 5 \
    -main-ratio    0.52 \
    -main-location left &
