#!/bin/zsh

riverctl map normal Super         Return spawn terminal
riverctl map normal Super+Shift   Return spawn "footclient"
riverctl map normal Super+Shift   E      spawn editor
riverctl map normal Super+Shift   B      spawn browser
riverctl map normal Super         P      spawn launcher
riverctl map normal Super+Shift   P      spawn fuzzel
riverctl map normal Super+Shift   R      spawn $HOME/.config/river/init
riverctl map normal Super+Shift   C      close
riverctl map normal Super+Shift   X      spawn logout_yad
riverctl map normal Super+Control X      exit

riverctl map normal Super       J focus-view next
riverctl map normal Super       K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map -repeat normal Super       H send-layout-cmd rivertile "main-ratio -0.0125"
riverctl map -repeat normal Super       L send-layout-cmd rivertile "main-ratio +0.0125"
riverctl map normal         Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal         Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map -repeat normal Super+Alt H move left  25
riverctl map -repeat normal Super+Alt J move down  25
riverctl map -repeat normal Super+Alt K move up    25
riverctl map -repeat normal Super+Alt L move right 25

riverctl map -repeat normal Super+Control H resize horizontal -25
riverctl map -repeat normal Super+Control L resize horizontal  25
riverctl map -repeat normal Super+Control K resize vertical   -25
riverctl map -repeat normal Super+Control J resize vertical    25

riverctl map normal Super Space toggle-float
riverctl map normal Super F     toggle-fullscreen

riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_RIGHT  resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# switch to workspace
riverctl map normal Super 1 spawn 'river-ws 1'
riverctl map normal Super 2 spawn 'river-ws 2'
riverctl map normal Super 3 spawn 'river-ws 3'
riverctl map normal Super 4 spawn 'river-ws 4'
riverctl map normal Super 5 spawn 'river-ws 5'
riverctl map normal Super 6 spawn 'river-ws 6'
riverctl map normal Super 7 spawn 'river-ws 7'
riverctl map normal Super 8 spawn 'river-ws 8'
riverctl map normal Super 9 spawn 'river-ws 9'

# send to workspace
riverctl map normal Super+Shift 1 spawn 'river-send 1'
riverctl map normal Super+Shift 2 spawn 'river-send 2'
riverctl map normal Super+Shift 3 spawn 'river-send 3'
riverctl map normal Super+Shift 4 spawn 'river-send 4'
riverctl map normal Super+Shift 5 spawn 'river-send 5'
riverctl map normal Super+Shift 6 spawn 'river-send 6'
riverctl map normal Super+Shift 7 spawn 'river-send 7'
riverctl map normal Super+Shift 8 spawn 'river-send 8'
riverctl map normal Super+Shift 9 spawn 'river-send 9'

# function keys
riverctl map normal None  Print                spawn 'screenshot'
riverctl map normal Super Print                spawn 'screenshot -s'
riverctl map normal Super+Shift Print          spawn 'screenshot -w 3'
riverctl map normal Super+Alt   Print          spawn 'screenshot -s -w 3'
riverctl map normal None XF86AudioRaiseVolume  spawn 'vol -u'
riverctl map normal None XF86AudioLowerVolume  spawn 'vol -d'
riverctl map normal None XF86AudioMute         spawn 'vol -m'
riverctl map normal None XF86MonBrightnessUp   spawn 'bright -u'
riverctl map normal None XF86MonBrightnessDown spawn 'bright -d'

riverctl background-color       0x191724 #191724
riverctl border-color-focused   0x6e6a86 #6e6a86
riverctl border-color-unfocused 0x403D52 #403D52

riverctl focus-follows-cursor always
riverctl hide-cursor when-typing enabled
riverctl xcursor-theme 'phinger-light' 30
riverctl border-width 2
riverctl attach-mode top
riverctl set-repeat 50 300
riverctl rule-add float -app-id 'pavucontrol*'
riverctl rule-add float -app-id 'xfce*'
riverctl rule-add float -app-id '*pacman*'
riverctl rule-add float -title 'Open File'
riverctl rule-add float -app-id 'yad*'
riverctl rule-add float -app-id '*byebye*'
riverctl rule-add ssd -app-id '*'
riverctl rule-add ssd -app-id '*emacs*'
riverctl rule-add ssd -app-id '*firefox*'
riverctl rule-add ssd -app-id 'pavucontrol*'
riverctl rule-add ssd -app-id 'xfce*'
riverctl rule-add ssd -app-id 'yad*'

riverctl default-layout rivertile

if [ -n "$(pgrep rivertile)" ]
then
  printf 'RIVERCTL: rivertile already running with pid %s\n' "$(pidof rivertile)"
else
  rivertile \
    -view-padding 6 \
    -outer-padding 6 \
    -main-count 1 \
    -main-ratio 0.5 >/dev/null 2>&1 &
fi

xrdb -merge $XDG_CONFIG_HOME/x/resources
udlaunch -u def
