#path-edit /opt/sw/rust/cargo/bin
#path-edit /opt/sw/nodejs/versions/current/bin
#path-edit /opt/sw/perl/versions/current/bin
#path-edit /opt/sw/go/versions/current/bin
#path-edit /opt/sw/zig/versions/current
#path-edit /opt/sw/bun/bin
#path-edit $GOPATH/bin
#path-edit /opt/sw/deno/bin
#path-edit ~/.local/share/homebrew/bin
#path-edit ~/.local/share/homebrew/sbin
