#!/bin/sh

swww init &

random_wallpaper "$(xdg-user-dir PICTURES)/wallpapers" &

dunst &

env -u WAYLAND_DISPLAY xfsettingsd &

mpd &

waybar -c ~/.config/hypr/waybar/config -s ~/.config/hypr/waybar/style.css &

emacs --fg-daemon &
