#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ' 1 ' ' 2 ' ' 3 ' ' 4 ' ' 5 ' ' 6 ' ' 7 ' ' 8 ' ' 9 '

bspc config border_width    1
bspc config window_gap      10

bspc config split_ratio     0.52

bspc config normal_border_color     '#26233A'
bspc config focused_border_color    '#403D52'
bspc config focused_border_color    '#403D52'

bspc config focus_follows_pointer   true

bspc rule --add Emacs state=tiled

xsetroot -cursor_name pointer &
hsetroot -fill ~/pictures/wallpapers/default.png &

xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/xorg/xresources" &

pgrep -x picom   > /dev/null || picom --vsync -b &
pgrep -x polybar > /dev/null || polybar &
pgrep -x xfsettinsd > /dev/null || xfsettingsd --daemon --replace --disable-wm-check &
xset r rate 300 50 &
