[metadata]
name = "gruvbox"
author = "wreed"
aliases = []
# GruvboxDarkHard
[colors]
foreground = "#ebdbb2"
background = "#1d2021"
cursor_bg = "#ebdbb2"
cursor_border = "#ebdbb2"
cursor_fg = "#665C54"
selection_bg = "#D65D0E"
selection_fg = "#EBDBB2"

ansi = ["#3C3836","#cc241d","#98971a","#d79921","#458588","#b16286","#689d6a","#a89984"]
brights = ["#928374","#fb4934","#b8bb26","#fabd2f","#83a598","#d3869b","#8ec07c","#ebdbb2"]
