# Case sensitive search if the search string contains uppercase characters.
SmartCaseSensitive: false

# Regular expression search.
RegexpSearch: false

# Incremental search.
Incsearch: true

#
# MemoryLimit: -1 # The maximum number of lines that can be loaded into memory.
# MemoryLimitFile: 100 # The maximum number of lines that can be loaded into memory when opening a file.
#
# DisableMouse: false # Disable mouse support.
# DisableColumnCycle: false # Disable cycling when moving columns.
#
ViewMode: markdown

Debug: false

Prompt:
  Normal:
#    ShowFilename: true # Show the filename.
#    InvertColor: true # Invert the color of the prompt.
#    ProcessOfCount: true # Show the process of count.

ShrinkChar: '…' # Characters displayed when the column is shrinking.

General:
  TabWidth: 4
  Header: 0
  AlternateRows: false
  ColumnMode: false
  LineNumMode: false
  WrapMode: true
  ColumnDelimiter: ","
  MarkStyleWidth: 1

# String of the color name: Foreground, Background, UnderlineColor
# Boolean: Bold, Blink, Dim, Italic, Underline
# Number: UnderlineStyle
StyleAlternate:
  Background: "gray"
StyleHeader:
  Bold: true
StyleOverStrike:
  Foreground: "aqua"
  UnderlineStyle: 0
  Bold: true
StyleOverLine:
  UnderlineStyle: 1
  Bold: true
  Foreground: "olive"
StyleSearchHighlight:
  Reverse: true
StyleColumnHighlight:
  Reverse: true
StyleMarkLine:
  Background: "maroon"
  Foreground: "black"
StyleSectionLine:
  Background: "navy"
  Foreground: "black"
StyleMultiColorHighlight:
  - Foreground: "red"
  - Foreground: "aqua"
  - Foreground: "yellow"
  - Foreground: "fuchsia"
  - Foreground: "lime"
  - Foreground: "blue"
  - Foreground: "grey"
StyleJumpTargetLine:
  Underline: false

# normal 8 colors
# 00 black:   black
# 01 red:     maroon
# 02 green:   green
# 03 yellow:  olive
# 04 blue:    navy
# 05 magenta: purple
# 06 cyan:    teal
# 07 white:   silver
  
# bright 8 colors
# 08 black: gray
# 09 red: red
# 10 green: lime
# 11 yellow: yellow
# 12 blue: blue
# 13 magenta: fuchsia
# 14 cyan: aqua
# 15 white: white

# Keybind
# Special key
#   "Enter","Backspace","Tab","Backtab","Esc",
#   "Delete", "Insert",
#   "Up", "Down", "Left", "Right", "Home", "End",
#   "F1...F64"
# Modifier key
#   "ctrl", "alt", "meta", "shift"
# Connect with modifier key + key
#   "ctrl+c"
KeyBind:
    exit:
        - "Escape"
        - "q"
    cancel:
        - "ctrl+c"
    write_exit:
        - "Q"
    set_write_exit:
        - "ctrl+q"
    suspend:
        - "ctrl+z"
    sync:
        - "r"
        - "ctrl+l"
    reload:
        - "R"
        - "ctrl+r"
    watch:
        - "T"
        - "ctrl+alt+w"
    watch_interval:
        - "ctrl+w"
    follow_mode:
        - "F"
    follow_all:
        - "ctrl+a"
    follow_section:
        - "F2"
    help:
        - "h"
        - "ctrl+alt+c"
    logdoc:
        - "ctrl+alt+e"
    down:
        - "e"
        - "ctrl+e"
        - "j"
        - "J"
        - "ctrl+j"
        - "Enter"
        - "Down"
    up:
        - "y"
        - "Y"
        - "ctrl+y"
        - "k"
        - "K"
        - "ctrl+K"
        - "Up"
    top:
        - "Home"
        - "g"
        - "<"
    bottom:
        - "End"
        - ">"
        - "G"
    left:
        - "left"
    right:
        - "right"
    half_left:
        - "ctrl+left"
    half_right:
        - "ctrl+right"
    page_up:
        - "PageUp"
        - "b"
        - "alt+v"
    page_down:
        - "PageDown"
        - "ctrl+v"
        - "alt+space"
        - "f"
        - "z"
    page_half_up:
        - "u"
        - "ctrl+u"
    page_half_down:
        - "d"
        - "ctrl+d"
    section_delimiter:
        - "alt+d"
    section_start:
        - "ctrl+F3"
        - "alt+s"
    section_header_num:
        - "F7"
    hide_other:
        - "alt+-"
    next_section:
        - "space"
    last_section:
        - "9"
    previous_section:
        - "^"
    mark:
        - "m"
    remove_mark:
        - "M"
    remove_all_mark:
        - "ctrl+delete"
    next_mark:
        - "alt+>"
    previous_mark:
        - "alt+<"
    set_view_mode:
        - "p"
        - "P"
    alter_rows_mode:
        - "C"
    line_number_mode:
        - "alt+n"
    search:
        - "/"
    wrap_mode:
        - "w"
        - "W"
    column_mode:
        - "c"
    backsearch:
        - "?"
    delimiter:
        - "d"
    header:
        - "H"
    skip_lines:
        - "ctrl+s"
    tabwidth:
        - "t"
    goto:
        - ":"
    next_search:
        - "n"
    next_backsearch:
        - "N"
    next_doc:
        - "]"
    previous_doc:
        - "["
    toggle_mouse:
        - "ctrl+alt+r"
    multi_color:
        - "."
    jump_target:
        - "alt+j"

Mode:
  markdown:
    SectionDelimiter: "^#"
    WrapMode: true
  psql:
    Header: 2
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
  mysql:
    Header: 3
    AlternateRows: true
    ColumnMode: true
    LineNumMode: false
    WrapMode: true
    ColumnDelimiter: "|"
