# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.1"
"rocks-git.nvim" = "2.5.2"
"rocks-config.nvim" = "3.1.0"

[plugins.web-devicons]
git = "nvim-tree/nvim-web-devicons"
rev = "v0.100"

[plugins.gitsigns]
git = "lewis6991/gitsigns.nvim"
rev = "v1.0.0"

[plugins.plenary]
git = "nvim-lua/plenary.nvim"
rev = "v0.1.4"

[plugins.onedark]
git = "navarasu/onedark.nvim"
rev = "67a74c275d1116d575ab25485d1bfa6b2a9c38a6"

[plugins.rosepine]
git = "rose-pine/neovim"
rev = "v3.0.2"

[plugins.gruvbox]
git = "morhetz/gruvbox"
rev = "v2.0.0"

[plugins.windline]
git = "windwp/windline.nvim"
rev = "1.1.0"

[plugins.autopairs]
git = "windwp/nvim-autopairs"
rev = "3d02855468f94bf435db41b661b58ec4f48a06b7"

[plugins.bufferline]
git = "akinsho/bufferline.nvim"
rev = "v4.9.1"

[plugins.telescope]
git = "nvim-telescope/telescope.nvim"
rev = "0.1.8"

[plugins.treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"

[plugins.highlight-colors]
git = "brenoprata10/nvim-highlight-colors"
rev = "68a4df620cf58e2c7336e53738e8cf3a522ad694"

[plugins.coq_nvim]
git = "ms-jpq/coq_nvim"
rev = "9e77f1f6196c4d4c17160aae82e18ae3f4916ce6"
branch = "coq"

[plugins.coq-artifacts]
git = "ms-jpq/coq.artifacts"
rev = "ef5f21d638ccc456cfa5b8d0ab37093cefe48c8b"
branch = "artifacts"

[plugins.lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v1.6.0"

[plugins.dracula]
git = "mofiqul/dracula.nvim"
rev = "515acae4fd294fcefa5b15237a333c2606e958d1"

[plugins.everforest]
git = "sainnhe/everforest"
rev = "v0.3.0"

[plugins.slimline]
git = "sschleemilch/slimline.nvim"
rev = "v1.2.0"

[plugins.todo-comments]
git = "folke/todo-comments.nvim"
rev = "v1.4.0"

[plugins.oil]
git = "stevearc/oil.nvim"
rev = "v2.14.0"

[plugins.alpha]
git = "goolord/alpha-nvim"
rev = "de72250e054e5e691b9736ee30db72c65d560771"

[plugins.kitty]
git = "fladson/vim-kitty"
rev = "v1.1"

[plugins.which-key]
git = "folke/which-key.nvim"
rev = "v3.16.0"

#[plugins.nui]
#git = "muniftanjim/nui.nvim"
#rev = "0.3.0"

#[plugins.notify]
#git = "rcarriga/nvim-notify"
#rev = "v3.15.0"

#[plugins.noice]
#git = "folke/noice.nvim"
#rev = "v4.10.0"

[config]
plugins_dir = "config/"
auto_setup = false


















